node(""){
    stage('build'){
        git("https://github.com/sobngwi/simple-maven-boot.git")
        sh('./mvnw clean install')
    }
    stage("deploy"){
        echo 'Deploying the artifact'
    }
    stage('Result'){
        junit("target/surefire-reports/TEST-*.xml")
        archive("target/*.jar")
    }
}